"""Regenerate the two seed pkls used by the placement pipeline.

This script produces:

    data/bc_snapshot_raster128.pkl   12,000 convex-convex pairs
    data/bo_train_pool_10k.pkl       10,000 concave-fs / convex-part pairs

Both pkls are lists of dicts with at least the keys

    fs_poly_wkt    WKT string of the free-space polygon, normalized to [-1, 1]
    part_poly_wkt  WKT string of the part polygon, in the same coordinate frame
    orig_idx       integer pair index

These are the only fields the report script (scripts/generate_placement_report.py)
and the smoke test (scripts/smoke_refine.py) read off the records.

Note: the original pkls used during the internship were generated by August's
local scripts and are not byte-identical to what this script produces. The
distribution and format match, so the rest of the pipeline (precompute, train,
report) runs against these regenerated pkls with no code changes. Validation
indices in the report script reference positions in the file, not specific
seeds, so the example pair IDs in the resulting PDF will differ.

Usage:
    python -m scripts.generate_seed_pkls

Optional flags:
    --n-convex N      Number of convex-convex pairs (default 12000)
    --n-concave N     Number of concave-convex pairs (default 10000)
    --seed S          Random seed (default 0)
    --out-dir DIR     Output directory (default data/)
"""
import argparse
import os
import pickle

import numpy as np
from shapely.affinity import scale, translate

from src.geometry.polygons import (
    random_convex_polygon,
    random_star_polygon,
    normalize_polygon_pair,
)


def _shrink_part_to_fit(fs_norm, part_norm, target_area_ratio_range=(0.05, 0.55)):
    """Scale the part down so its area is a sensible fraction of the free space.

    The placement model only matters when the part actually fits, so we sample
    an area ratio uniformly in `target_area_ratio_range` and scale the part to
    hit it. Returns the rescaled part polygon, still centered at the origin.
    """
    if not fs_norm.is_valid or not part_norm.is_valid:
        return part_norm
    if fs_norm.area <= 0 or part_norm.area <= 0:
        return part_norm

    target_ratio = np.random.uniform(*target_area_ratio_range)
    target_area = target_ratio * fs_norm.area
    factor = float(np.sqrt(target_area / part_norm.area))
    return scale(part_norm, factor, factor, origin=(0, 0))


def _center_at_origin(poly):
    c = poly.centroid
    return translate(poly, -c.x, -c.y)


def _make_convex_pair(rng):
    """One convex-convex pair, normalized to [-1, 1] for the free space."""
    n_fs = int(rng.integers(5, 12))
    n_part = int(rng.integers(4, 10))
    fs_raw = random_convex_polygon(n_vertices=n_fs, radius=100.0)
    part_raw = random_convex_polygon(n_vertices=n_part, radius=60.0)
    fs_norm, part_norm = normalize_polygon_pair(fs_raw, part_raw)
    part_norm = _shrink_part_to_fit(fs_norm, _center_at_origin(part_norm))
    return fs_norm, part_norm


def _make_concave_pair(rng):
    """One concave-fs / convex-part pair, normalized to [-1, 1] for the fs."""
    n_points = int(rng.integers(4, 8))
    outer = 100.0
    inner = float(rng.uniform(30.0, 55.0))
    fs_raw = random_star_polygon(n_points=n_points, outer_r=outer, inner_r=inner)
    if not fs_raw.is_valid:
        fs_raw = fs_raw.buffer(0)

    n_part = int(rng.integers(4, 9))
    part_raw = random_convex_polygon(n_vertices=n_part, radius=50.0)
    fs_norm, part_norm = normalize_polygon_pair(fs_raw, part_raw)
    part_norm = _shrink_part_to_fit(fs_norm, _center_at_origin(part_norm))
    return fs_norm, part_norm


def generate_pkl(n_pairs, kind, seed, out_path):
    """Write `n_pairs` records of the given kind to `out_path`.

    kind is "convex" or "concave".
    """
    rng = np.random.default_rng(seed)
    np.random.seed(seed)  # the polygon primitives use numpy global state

    records = []
    attempts = 0
    while len(records) < n_pairs:
        attempts += 1
        try:
            if kind == "convex":
                fs, part = _make_convex_pair(rng)
            elif kind == "concave":
                fs, part = _make_concave_pair(rng)
            else:
                raise ValueError(kind)
        except Exception:
            continue

        if (not fs.is_valid) or (not part.is_valid) or fs.is_empty or part.is_empty:
            continue
        if fs.area <= 0 or part.area <= 0:
            continue
        if part.area >= fs.area:
            continue

        records.append({
            "fs_poly_wkt": fs.wkt,
            "part_poly_wkt": part.wkt,
            "orig_idx": len(records),
        })
        if len(records) % 1000 == 0:
            print(f"  {kind}: {len(records)} / {n_pairs}", flush=True)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "wb") as f:
        pickle.dump(records, f, protocol=pickle.HIGHEST_PROTOCOL)

    size_mb = os.path.getsize(out_path) / (1024 * 1024)
    print(
        f"wrote {n_pairs} {kind} pairs to {out_path} "
        f"({size_mb:.1f} MB, {attempts} attempts)",
        flush=True,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-convex", type=int, default=12000)
    ap.add_argument("--n-concave", type=int, default=10000)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out-dir", default="data")
    args = ap.parse_args()

    generate_pkl(
        args.n_convex, "convex", args.seed,
        os.path.join(args.out_dir, "bc_snapshot_raster128.pkl"),
    )
    generate_pkl(
        args.n_concave, "concave", args.seed + 1,
        os.path.join(args.out_dir, "bo_train_pool_10k.pkl"),
    )
    print("done. you can now run scripts/generate_placement_report.py.")


if __name__ == "__main__":
    main()
